### ISSUE TITLE
Cloudflare redirects

### ISSUE THREAD

**Issue by andrewward** [tomhillable/consul-rpm#10]
Seems that cloudflare's redirects breaks spectool's ability to download the files from dl.bintray.com.

Had to do:
```
wget https://dl.bintray.com/mitchellh/consul/0.5.0_web_ui.zip -O ~/rpmbuild/SOURCES/0.5.0_web_ui.zip
wget https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip -O ~/rpmbuild/SOURCES/0.5.0_linux_amd64.zip
```

This was on a Centos 6.4 server

**Comment by phrawzty** [comment]
Weird! I just tried it on a fresh CentOS 7 box in AWS and `spectool -g -R consul.spec` works just fine, which is to say, it downloads the archives as expected.

Perhaps it's something specific CentOS 6.x's curl lib?

**Comment by andrewward** [comment]
Must be.

I'm on version rpmdevtools-7.5-2.el6.noarch, and curl-7.19.7-37.el6_4.x86_64.

It's actually trying to write the file name as whatever they reference it as in the cache:

```
Cannot write to “/home/award/rpmbuild/SOURCES/55ae1d1de29a3a50388956262cfcb2bb6f4c34f3?response-content-disposition=attachment;filename="0.5.0_web_ui.zip"&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNTVhZTFkMWRlMjlhM2E1MD
M4ODk1NjI2MmNmY2IyYmI2ZjRjMzRmMz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMjAuNS4wX3dlYl91aS56aXAlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0MjcyMTcxNjJ9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&S
ignature=T1sFDHuratUH7hsUJKDWxxZCXhtIG6Dd-wlOWRapy5GxhVKI1iFZEUZygGq2Ota5rQGaSI6QfmlwmwpEbs3OpIXL10c5nj~HRbgXi~9Xs2CopXmF7JR0a6-qFwEvf1G3me~dZjC0oi3KfoS-V~E8fsJA2KV~qgFL1ossZoXoGSUEk6QOC0HWd3HU3R7fbo2f1C5Y~LR1AjiIUwsNzsugQZ79d0dSBB6y8cmUTLMJvCCQ1DM37drb9X5wVncMfCmLEi7KwBq
hLNByGrS3R6FnoD0TllRhLI8UbQ4c07JIhX0pe8U01WZmhI0YVMWMkeh6iNJoTOUkpJyufkCiVbTjwQ__&Key-Pair-Id=APKAIQIOJCQ5764M5VTQ”
```

It's not really a big deal, just thought I'd bring it up. Thanks for the spec!

**Comment by duritong** [comment]
I had the issue as well on EL 6, question is if we can have a working url? Probably not, as we should have a working tool... ;-)
