### ISSUE TITLE
Suggestion: Provide a logrotate file

### ISSUE THREAD

**Issue by cruatta** [tomhillable/consul-rpm#14]
Since we're logging the output of consul to a file, I think it would be convenient to add a logrotate file to the RPM and automatically add it to /etc/logrotate.d. Thoughts?

**Comment by duritong** [comment]
But only on el6, el7 goes to syslog, not? Shouldn't we just in general log to syslog?

**Comment by cruatta** [comment]
That's fine with me. I was just suggesting this because of the way things are setup currently but syslog would be preferable. I will close this issue and create a ticket about logging to syslog on el6.
