### ISSUE TITLE
Consul not starting

### ISSUE THREAD

**Issue by DaveBlooman** [tomhillable/consul-rpm#23]
Hi,

I am trying to run this in server mode on centos7 with the following cmd options

`CMD_OPTS="agent -server -bootstrap-expect 1 -config-dir=/etc/consul -data-dir=/var/lib/consul`

I install the rpm, but the service doesn't start on boot, but will start when i manually start it.  On boot, when i look at the status, it indicates it is dead.  Have you tried the rpm in server mode?

**Comment by duritong** [comment]
I do run it in server mode and it works. What is the error that you are getting? Like output if systemctl status consul

**Comment by DaveBlooman** [comment]
```sh 
consul.service - Consul is a tool for service discovery and configuration. Consul is distributed, highly available, and extremely scalable.
   Loaded: loaded (/usr/lib/systemd/system/consul.service; disabled)
   Active: inactive (dead)
     Docs: http://www.consul.io
```

**Comment by duritong** [comment]
So this is after a reboot?

Well, services should not be automatically registered to be started at boot-time (which is also what the disabled says in the Loaded line), as well as services should not be started automatically after installing the rom..

So if you want to have it started at boot time, you need to:

    systemctl enable consul

As well as you need todo a

    systemctl start consul

if you want to have the service running.

This is the default behavior of services on RPM-based distributions and we should follow it.

Given that I think everything works as it should I'm going to close that bug.

**Comment by DaveBlooman** [comment]
Looking at the spec, I thought it would do this for me in the post block.

**Comment by duritong** [comment]
Nope, it only register it as a service to be used by either systemd or chkconfig.
