### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by simonsm1** [tomhillable/consul-rpm#32]
Hi,

Any chance of adding a license to the project, just so we know where we stand when using it?

Many Thanks

**Comment by phrawzty** [comment]
Consul itself is licensed under the [MPL](https://github.com/hashicorp/consul/blob/master/LICENSE) - if there are no objections, I propose that we use the same for this repo. @duritong @tomhillable ?

**Comment by tomhillable** [comment]
:+1: @phrawzty - I'd be up for using the same license and keeping this repo in line with Consul

**Comment by simonsm1** [comment]
Thanks for adding.

The file that has been added though appears to be the source html of a github page which has the MPL on it. Was this intended?

**Comment by duritong** [comment]
Ups, clearly not reviewed good enoug. Will fix it.

**Comment by phrawzty** [comment]
HA omg I totally messed that one up.  Sorry.  Fixing now.
