### ISSUE TITLE
init script for consul-template is broken

### ISSUE THREAD

**Issue by kostyrevaa** [tomhillable/consul-rpm#42]
[prog name](https://github.com/tomhillable/consul-rpm/blob/master/SOURCES/consul-template.init#L26)
[wait check](https://github.com/tomhillable/consul-rpm/blob/master/SOURCES/consul-template.init#L67)
starting service
```
sh -x /etc/init.d/consul-template start
+ netstat -nptl
+ grep -q '^tcp.*:8400.*LISTEN \+9873\/consul-template'
+ sleep 1
```
```
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
consul  6403 consul   15u  IPv4  32419      0t0  TCP 127.0.0.1:8400 (LISTEN)
```
infinite loop

**Comment by duritong** [comment]
Can you test by making `grep -q` a `grep -qi`? As tcp seems to be uppercase in your output.

**Comment by duritong** [comment]
Or what is actually your `netstat -nlpt` output?

**Comment by kostyrevaa** [comment]
consul listens to 8400 and not consul-template. The latter never listens to any ports.

**Comment by duritong** [comment]
you're right! :) thanks for reporting
