### ISSUE TITLE
Update for current releases

### ISSUE THREAD

**Issue by szechyjs** [tomhillable/consul-rpm#64]
v0.9.2 is no longer the latest release.

The following have been released since:
- 0.9.3
- 1.0.0
- 1.0.1

**Comment by epleterte** [comment]
You can easily get/build i.e. 1.0.1 by passing `--define "_version 1.0.1"` to (both) `spectool` and `rpmbuild` :)

**Comment by duritong** [comment]
and make a PR, thanks!

**Comment by epleterte** [comment]
...here you go! :)
