### ISSUE TITLE
Restrict executable permission

### ISSUE THREAD

**Issue by alexandrustaetu** [tomhillable/consul-rpm#66]
Hello,

Thanks for this great repo, cut some time on deploying consul on a number of machines.
Would it be ok for a pull request on having additional parameters for the build process? 

As an example, it would help having the possibility to set consul binary file mod to 750 where the servers can be accessed by non sudoers.

Let me know if this change adheres to this repo's guidelines and if a pull request should be created.

Thanks,
Alex.

**Comment by dekimsey** [comment]
👎 

I don't think this makes sense. A user could just drop the go binary onto the system and completely bypass whatever this is trying to restrict. As far as I know, running consul from a userspace different than the daemon doesn't leak anything.

**Comment by alexandrustaetu** [comment]
This makes sense on multi multi-tenancy  environments, where you have consul and it's configs ( storing auth tokens ) protected by chown and chmod. Any user may drop whatever consul binaries on any paths in the system, without a valid token not much harm can be done.

**Comment by alexandrustaetu** [comment]
You are right, having another consul bin on the server bypasses the requested feature, closing this issue.

**Comment by duritong** [comment]
What folks ended up doing is restricting access to the consul ports to certain uids. See some ideas here: https://www.mauras.ch/securing-consul.html
(besides what consul already provides).
